services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD : ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE : ${DATABASE_NAME}
      MYSQL_USER : ${DATABASE_USER}
      MYSQL_PASSWORD : ${DATABASE_PASSWORD}

  backend:
    build: muthubala2004/backend:latest
    container_name: backend
    env_file:
      - .env
    depends_on:
      - mysql

  frontend:
    build: muthubala2004/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx-react.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend